### PR TITLE
various

### PR DESCRIPTION
**Pull request by fschwiet**
Hi, I started using JoeBlogs to export data.  I've made some modifications I thought you might like.  Thanks for making your code available on github.
- the console and integration test projects are now using .NET 4.0, because I needs it
- I moved the console code into a new console application that makes it easier to add different commands (using ManyConsole, a library I have on nuget)
- loading comment statuses works now, and I have an integration test verifying that.
  - I think the style of integration testing might be helpful for you otherwise, it allows faking the wordpress server to verify the code end-to-end
- some other minor fixes (I had to deal with wordpress post IDs not fitting in a int32, and some other issue I forget)

### CODE REVIEW

**Comment by fschwiet** [comment]
There's also a nuspec in there now for making a nuget package to put this onto nuget.  I don't know if you're interested in publishing to nuget, or mind if I would.  If you want, I can publish.  Its a good way to make the code visible to .net developers.

**Comment by alexjamesbrown** [comment]
Looks good...
Only thing is ideally we'll take the nuget packages out of the repo-
http://coderjournal.com/2011/12/cleaning-up-your-git-repository-for-nuget-1-6/

there's loads of other "best practices" stuff about this...

any ideas?

**Comment by fschwiet** [comment]
I haven't tried using package restore, though it has some benefits I'm not completely sure.  I believe the benefit is reducing repo size.  One risk is that nuget might take down a package (though this is controversial, I do know of at least one package that I have a dependency on thats been removed from the nuget servers).  Personally I haven't found it worth the bother.

**Comment by kevininspace** [comment]
Nice work fellas.

**Comment by alexjamesbrown** [comment]
great, thanks!
Would be interested in nuget if you'd like to help?

**Comment by fschwiet** [comment]
My personal backlog is kind of full right now, and there is nothing WordPress related, so I'm not sure when I'll be revisiting the project.  Thanks for pulling in my changes though, I help they help.

**Pull request merged**
